### PR TITLE
rename hello-nginx.yaml to hello-nginx.yml

### PR DESCRIPTION
**Pull request by kadel**
we should use yml extension for all YAML files

### CODE REVIEW

**Comment by tnozicka** [comment]
I believe in the exact opposite. We should use `yaml`

**Comment by kadel** [comment]
ok, so it looks like that official recomendation is yaml extension, you are right ;-)

**Comment by kadel** [comment]
closing this :-D

**Comment by tnozicka** [comment]
@kadel also https://github.com/redhat-developer/opencompose/blob/master/examples/wordpress/no-storage.yml has wrong extension

**Comment by kadel** [comment]
yep, I just noticed that. Will fix it

**Pull request closed without merging**
