### PR TITLE
Update community info in README

### PR DESCRIPTION
**Pull request by surajssd**
Add info about irc and remove slack info.

### CODE REVIEW

**Comment by kadel** [comment]
I think we can keep slack there, no? most of us are in sig-apps channel

**Comment by surajssd** [comment]
But it is not the channel we should be using IMHO, because if someone comes and asks question about opencompose and there no-one else than just us who have the idea about opencompose.

So someone asking question might not get the answer, also it increases our work to monitor the slack for opencompose questions all the time. So I would want folks to come to specific channel for asking questions. That would save everyone from wasting time.

**Comment by tnozicka** [comment]
I think we should add #opencompose to readme; I don't have a strong opinion on whether to remove or leave slack #sig-apps.

**Comment by surajssd** [comment]
Closing since the project is now discontinued!

**Pull request closed without merging**
