### PR TITLE
Updated .gitignore file

### PR DESCRIPTION
**Pull request by surajssd**
Added things to ignore from golang, vim and intellij.

### CODE REVIEW

**Review by tnozicka — DISMISSED** [review]
@surajssd None of it belongs to project .gitignore file. For things specific to your editor and setup use global .gitignore like:
```bash
git config --global core.excludesfile '~/.gitignore'
```

**Comment by tnozicka** [comment]
For clarification only artifacts created by the project itself (e.g. by running `make build`) belong to project's `.gitignore`.

**Comment by cdrage** [comment]
@tnozicka 
Seems pretty inline to https://raw.githubusercontent.com/kubernetes/kubernetes/master/.gitignore as well as https://raw.githubusercontent.com/openshift/origin/master/.gitignore I can go on with more examples.

Counter-argument would be that `git config --global core.excludesfile '~/.gitignore'` wouldn't necessarily be the same for each project. For example, using Sublime Text for HTML in a certain project vs Vim with code (that's what I use), or Eclipse for Java. Files created by each-editor and/or build process may be either falsely included or falsely not.

**Comment by surajssd** [comment]
@tnozicka I didn't knew this, TIL

**Comment by tnozicka** [comment]
@cdrage sad to head about k8s :(

You shall not pollute the project with files not relevant to other developers. Working on 100 different projects you would have to pollute them all in order to ignore your `.idea/` folder instead of setting it **once** in your local .gitignore file.

> Counter-argument would be that git config --global core.excludesfile '~/.gitignore' wouldn't necessarily be the same for each project. 

Not really sure what you mean here. But that's a **global file** and you ignore e.g. tmp files **across** repositories.
Like:
```bash
.idea/*
*.iml
*.swp
```

**Comment by cdrage** [comment]
Can we *at least* include `*.swp`? Safe to say that is applicable to other developers too.

Even the largest Go project includes this: https://raw.githubusercontent.com/docker/docker/master/.gitignore

See:
```
.bashrc
.editorconfig
.gopath/
.go-pkg-cache/
```

Despite them also recommending using a global configuration file, they at least go through the standards of ignoring locally committed files.

Respectfully, if projects such as OpenShift, Docker and Kubernetes (the largest Go projects out there) use local .gitignore's to ignore unwanted files, then I don't believe adding a few lines to .gitignore is going to clutter ours.

**Comment by kadel** [comment]
I don't see reason why not put this to `.gitignore`. 
It makes sure that no one commits files that you don't want commited to you repo, regardless what his git configuration is.

**Comment by surajssd** [comment]
@kadel true :+1:

**Comment by cdrage** [comment]
@tnozicka @kadel @surajssd 

Re-open and have this discussed? I believe most of us agree that having a local .gitignore is beneficial. Especially for outside developers looking to contribute to OpenCompose.

**Comment by surajssd** [comment]
rebased with current master!

**Comment by cdrage** [comment]
@kadel Want to do a quick review and possible merge?

This LGTM :+1:

**Comment by kadel** [comment]
lets go with this. Majority of us thinks this will be beneficial.
Plus this is really stupid think to spend time with arguing about :sunglasses:

**Review by kadel — APPROVED** [review]

**Pull request merged**
