### PR TITLE
Added go lint in makefile

### LINKED ISSUE #104: Adding `go lint` in makefile

### PR DESCRIPTION
**Pull request by surajnarwade**
Resolves #104

### CODE REVIEW

**Comment by surajnarwade** [comment]
cc @kadel @cdrage @surajssd 
 needs review.

**Comment by kadel** [comment]
I'm not sure if it makes sense to run golint in travis. It doesn't make sense to enforce all golint rules as stated  in projects readme:

> We will not be adding pragmas or other knobs to suppress specific warnings, so do not expect or require code to be completely "lint-free
>In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process

If we can't enforce all the rules does it make sense to have it in travis-ci where it just generates a lot of warnings on which no one is going to look at?

**Comment by kadel** [comment]
What do you think @surajnarwade @surajssd @containscafeine ?

**Comment by surajssd** [comment]
@kadel @surajnarwade Add it to local testing as opposed to travis!

**Pull request closed without merging**
